export const TodoActionTypes = {
  ADD_TODO: 'ADD_TODO',
  GET_TODOS: 'GET_TODOS',
  GET_TODO: 'GET_TODO',
  SET_LOADING: 'SET_LOADING',
  TODOS_ERROR: 'TODOS_ERROR',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
};
